#include<iostream>
#include<string>
#include<random>
#include<chrono> //seeding with time point
#include<algorithm>
#include<cmath>
#include<array>
#include<vector>

//main writing interface
#include<OVFWriter.h>
//and reading, just cause
#include<OVFParser.h>

#if defined(WIN32)
#define FILE_PATH_SEPARATOR '\\'
#else
#define FILE_PATH_SEPARATOR '/'
#endif

//TODO implement a macro to allow UTF-16 argv on windows!
int main(int argc, char** argv)
{
    //directory for testing file interfacing options
    if(argc != 2)
    {
        std::cerr << "Expected at least (and only) one argument(working directory), aborting!\n";
        return 1;
    }
    std::string workingDir { argv[1] };
    if( workingDir.back() != FILE_PATH_SEPARATOR ||
        workingDir.back() == '\"' && *(workingDir.end() - 2) == FILE_PATH_SEPARATOR )
        workingDir += FILE_PATH_SEPARATOR;

    //form test data
    VField::VField testOVF;
    {
        //begin with header, set it in-place using reference
        VField::OVFHeader& ref { testOVF.header() };
        //set it to OVF 1.0 later for tests
        ref.set(VField::OVFParameter::Title, "An assortment of random unitary vectors");
        ref.set(VField::OVFParameter::Desc, "Generated by the power of castle Grayskull\n"
                                            "\"I don't like to feel good. I like to feel evil.\"\n"
                                            "--Skeletor, 1985" ); //multiline description for testing
        //set mesh unit after adding the data in
        ref.set(VField::OVFParameter::Munit, "nm"); //nanometers
        ref.set(VField::OVFParameter::Vlabels, "Rx Ry Rz");
        ref.set(VField::OVFParameter::Vunit, "\"a.u.\" \"a.u.\" \"a.u.\"");

        //and now for mesh parameters
        ref.set(VField::OVFParameter::Vdim,   VField::parameter_cpp_type_t<VField::ParameterType::Unsigned>{3}  );
        ref.set(VField::OVFParameter::Xnodes, VField::parameter_cpp_type_t<VField::ParameterType::Unsigned>{256});
        ref.set(VField::OVFParameter::Ynodes, VField::parameter_cpp_type_t<VField::ParameterType::Unsigned>{256});
        ref.set(VField::OVFParameter::Znodes, VField::parameter_cpp_type_t<VField::ParameterType::Unsigned>{8}  );
        ref.setMeshType(VField::MeshType::Rectangular);

        //and for coordinate grid
        ref.set(VField::OVFParameter::Xbase, 1.);
        ref.set(VField::OVFParameter::Ybase, 1.);
        ref.set(VField::OVFParameter::Zbase, 1.);
        ref.set(VField::OVFParameter::Xstep, 2.);
        ref.set(VField::OVFParameter::Ystep, 2.);
        ref.set(VField::OVFParameter::Zstep, 2.);

        //and numeric limits/boundaries
        ref.set(VField::OVFParameter::Xmin, 0.);
        ref.set(VField::OVFParameter::Ymin, 0.);
        ref.set(VField::OVFParameter::Zmin, 0.);
        ref.set(VField::OVFParameter::Xmax, 512.);
        ref.set(VField::OVFParameter::Ymax, 512.);
        ref.set(VField::OVFParameter::Zmax, 512.);
        ref.set(VField::OVFParameter::Vmin, 1.);
        ref.set(VField::OVFParameter::Vmax, 1.);
        ref.set(VField::OVFParameter::Vmult, 1.);
        //Header done, kind-of
    }
    {
        //and then do the random data generation
        const std::size_t pCount {
                      testOVF.header().requireAs<std::size_t>(VField::OVFParameter::Xnodes) *
                      testOVF.header().requireAs<std::size_t>(VField::OVFParameter::Ynodes) *
                      testOVF.header().requireAs<std::size_t>(VField::OVFParameter::Znodes)
                      };
        const std::size_t pDim { testOVF.header().requireAs<std::size_t>(VField::OVFParameter::Vdim) };
        //then initialize data using init interface
        testOVF.initData<double>( pCount * pDim );
        //let the randOOm generation begin!
        std::default_random_engine generator( std::chrono::duration_cast<std::chrono::milliseconds>( 
                    std::chrono::system_clock::now().time_since_epoch()
                ).count() );//seeded with milliseconds from unix epoch start
        std::normal_distribution<double> fieldDist(0.0, 1.0);  //0.0 mean and 1.0 st. deviation
        //fill the field point by point through its multidimensional view
        auto points = testOVF.pointView<double>();
        for(std::size_t point = 0; point < points.extent(0); ++point)
        {
            double nrm {0.0};
            for(std::size_t i = 0; i < pDim; i++)
            {
                points[point, i] = fieldDist(generator);
                nrm += points[point, i] * points[point, i];
            }
            nrm = std::sqrt(nrm);
            for(std::size_t i = 0; i < pDim; i++)
                points[point, i] /= nrm;
        }
    }
    //Mixed-version ranges are rejected without rewriting either input header.
    std::vector<VField::VField> mixedVersions{testOVF, testOVF};
    mixedVersions[1].header().setVersion(VField::OVFVersion::OVF1);
    const auto mixedResult = writeOVF(workingDir + "mixed.ovf", mixedVersions);
    if(mixedResult ||
       mixedResult.error().code != VField::WriteErrorCode::IncompatibleVersions ||
       mixedVersions[0].header().version() != VField::OVFVersion::OVF2 ||
       mixedVersions[1].header().version() != VField::OVFVersion::OVF1)
    {
        std::cerr << "Mixed-version range writing modified or accepted its input!\n";
        return 15;
    }

    //try writing ovf out in file named tmpOVF.ovf
    auto writeResult {writeOVF(workingDir + "tmpOVF2.ovf", testOVF)};
    if(!writeResult)
    {
        std::cerr << "Got some errors while exporting an ovf2:\n" << writeResult.error().message;
        return 2;
    }

    //try reading it back
    auto opened = VField::VFieldFile::open(workingDir + "tmpOVF2.ovf");
    if(!opened)
    {
        std::cerr << "Got errors reading the file:\n" << opened.error().message << "\n";
        return 3;
    }
    auto readBack = std::move(*opened);
    auto fieldsResult = readBack.fields();
    if(!fieldsResult || fieldsResult->size() != 1 ||
       !fieldsResult->front().isDataPresent())
    {
        std::cerr << "VFieldFile span access failed!\n";
        return 7;
    }

    const auto fields = *fieldsResult;
    auto fileCopy = std::as_const(readBack).fieldsCopy();
    if(!fileCopy || fileCopy->size() != fields.size() ||
       fileCopy->front() != fields.front())
    {
        std::cerr << "VFieldFile copy with unique ownership failed!\n";
        return 8;
    }
    if(!readBack.unload(0) || readBack.dataLoaded(0) || !readBack.dataAvailable(0) ||
       readBack.unload(readBack.segmentCount()))
    {
        std::cerr << "Unfetch did not preserve lazy reload metadata!\n";
        return 13;
    }
    if(auto loaded = readBack.load(0); !loaded || !loaded->get().isDataPresent())
    {
        std::cerr << "Unfetched segment could not be fetched again!\n";
        return 14;
    }

    constexpr std::size_t sliceFirst = 7;
    constexpr std::size_t sliceCount = 5;
    const auto sliceDimension = testOVF.pointDimension();
    const auto contiguousSlice = readBack.readSlice(0, sliceFirst, sliceCount);
    if(!contiguousSlice)
    {
        std::cerr << "Contiguous slice read failed: " << contiguousSlice.error().message << "\n";
        return 9;
    }
    const auto sourcePoints = std::as_const(testOVF).pointView<double>();
    const auto slicedPoints = std::as_const(*contiguousSlice).pointView<double>();
    if(slicedPoints.extent(0) != sliceCount || slicedPoints.extent(1) != sliceDimension)
    {
        std::cerr << "Contiguous slice has unexpected dimensions!\n";
        return 9;
    }
    for(std::size_t point = 0; point < sliceCount; ++point)
        for(std::size_t component = 0; component < sliceDimension; ++component)
            if(slicedPoints[point, component] != sourcePoints[sliceFirst + point, component])
            {
                std::cerr << "Contiguous slice contains unexpected data!\n";
                return 10;
            }
    //and compare to original data, by first writing and then reading back
    auto BareOVF2 = std::as_const(readBack).copy(0).value();
    if(auto rewriteResult = writeOVF(workingDir + "tmpOVF2.ovf", testOVF); !rewriteResult)
    {
        std::cerr << "Got errors rewriting the OVF2 file:\n" << rewriteResult.error().message;
        return 11;
    }
    if(!readBack.read(workingDir + "tmpOVF2.ovf") ||
       BareOVF2 != readBack.load(0).value().get())
    {
        std::cerr << "While testing OVF2 read back different data!\n";
        return 4;
    }
    //success with OVF2 parsing by this point, try OVF1 for kicks too
    testOVF.header().set(VField::OVFParameter::VersionString, "# OOMMF: rectangular mesh v1.0");
    writeResult = writeOVF(workingDir + "tmpOVF1.ovf", testOVF);
    if(!writeResult)
    {
        std::cerr << "Got some errors while exporting an ovf1:\n" << writeResult.error().message;
        return 5;
    }
    if(!readBack.read(workingDir + "tmpOVF1.ovf")) return 5;
    auto BareOVF1 = std::as_const(readBack).copy(0).value();
    if(auto rewriteResult = writeOVF(workingDir + "tmpOVF1.ovf", testOVF); !rewriteResult)
    {
        std::cerr << "Got errors rewriting the OVF1 file:\n" << rewriteResult.error().message;
        return 12;
    }
    if(!readBack.read(workingDir + "tmpOVF1.ovf") ||
       BareOVF1 != readBack.load(0).value().get())
    {
        std::cerr << "While testing OVF1 read back different data!\n";
        return 6;
    }
    //success handling OVF1

    return 0;
}
