#include<iostream>
#include<string>
#include<random>
#include<chrono> //seeding with time point
#include<algorithm>
#include<cmath>
#include<array>

//main writing interface
#include<OVFWriter.h>
//and reading, just cause
#include<OVFParser.h>

#if defined(WIN32)
#define FILE_PATH_SEPARATOR '\\'
#else
#define FILE_PATH_SEPARATOR '/'
#endif

//TODO implement a macro to allow UTF-16 argv on windows!
int main(int argc, char** argv)
{
    //directory for testing file interfacing options
    if(argc != 2)
    {
        std::cerr << "Expected at least (and only) one argument(working directory), aborting!\n";
        return 1;
    }
    std::string workingDir { argv[1] };
    if( workingDir.back() != FILE_PATH_SEPARATOR ||
        workingDir.back() == '\"' && *(workingDir.end() - 2) == FILE_PATH_SEPARATOR )
        workingDir += FILE_PATH_SEPARATOR;

    //form test data
    VField::VField testOVF;
    {
        //begin with header, set it in-place using reference
        VField::OVFHeader& ref { testOVF.Header };
        //set it to OVF 1.0 later for tests
        ref.set(VField::OVFParameter::VersionString, "# OOMMF OVF 2.0");
        ref.set(VField::OVFParameter::Title, "An assortment of random unitary vectors");
        ref.set(VField::OVFParameter::Desc, "Generated by the power of castle Grayskull\n"
                                            "\"I don't like to feel good. I like to feel evil.\"\n"
                                            " --Skeletor, 1985" ); //multiline description for testing
        //set mesh unit after adding the data in
        ref.set(VField::OVFParameter::Munit, "nm"); //nanometers
        ref.set(VField::OVFParameter::Vlabels, "Rx Ry Rz");
        ref.set(VField::OVFParameter::Vunit, "\"a.u.\" \"a.u.\" \"a.u.\"");

        //and now for mesh parameters
        ref.set(VField::OVFParameter::Vdim,   3lu  );
        ref.set(VField::OVFParameter::Xnodes, 256lu);
        ref.set(VField::OVFParameter::Ynodes, 256lu);
        ref.set(VField::OVFParameter::Znodes, 8lu  );
        ref.setMesh(VField::OVFHeader::MeshType::rectangular);

        //and for coordinate grid
        ref.set(VField::OVFParameter::Xbase, 1.);
        ref.set(VField::OVFParameter::Ybase, 1.);
        ref.set(VField::OVFParameter::Zbase, 1.);
        ref.set(VField::OVFParameter::Xstep, 2.);
        ref.set(VField::OVFParameter::Ystep, 2.);
        ref.set(VField::OVFParameter::Zstep, 2.);

        //and numeric limits/boundaries
        ref.set(VField::OVFParameter::Xmin, 0.);
        ref.set(VField::OVFParameter::Ymin, 0.);
        ref.set(VField::OVFParameter::Zmin, 0.);
        ref.set(VField::OVFParameter::Xmax, 512.);
        ref.set(VField::OVFParameter::Ymax, 512.);
        ref.set(VField::OVFParameter::Zmax, 512.);
        ref.set(VField::OVFParameter::Vmin, 1.);
        ref.set(VField::OVFParameter::Vmax, 2.);
        ref.set(VField::OVFParameter::Vmult, 1.);
        //Header done, kind-of
    }
    {
        //and then do the random data generation
        const std::size_t pCount {
                      testOVF.Header.getUint(VField::OVFParameter::Xnodes) *
                      testOVF.Header.getUint(VField::OVFParameter::Ynodes) *
                      testOVF.Header.getUint(VField::OVFParameter::Znodes) 
                      };
        const std::size_t pDim { testOVF.Header.getUint(VField::OVFParameter::Vdim) };
        //then initialize data using init interface
        testOVF.initData<double>( pCount * pDim );
        //let the randOOm generation begin!
        std::default_random_engine generator( std::chrono::duration_cast<std::chrono::milliseconds>( 
                    std::chrono::system_clock::now().time_since_epoch()
                ).count() );//seeded with milliseconds from unix epoch start
        std::normal_distribution<double> fieldDist(0.0, 1.0);  //0.0 mean and 1.0 st. deviation
        //filling data in with iterators for once Pog
        const auto EndIt = testOVF.end<double>();
        for(auto it = testOVF.begin<double>(); it != EndIt; ++it)
        {
            double nrm {0.0};
            for(std::size_t i = 0; i < pDim; i++)
            {
                it[i] = fieldDist(generator);
                nrm += it[i] * it[i];
            }
            nrm = std::sqrt(nrm);
            for(std::size_t i = 0; i < pDim; i++)
                it[i] /= nrm;
        }
    }
    //try writing ovf out in file named tmpOVF.ovf
    auto write_log {WriteOVF(workingDir + "tmpOVF.ovf", testOVF)};
    if(!write_log.empty())
    {
        std::cerr << "Got some errors while exporting an ovf:\n" << write_log;
        return 2;
    }

    //try reading it back
    VField::VFieldFile readBack(workingDir + "tmpOVF.ovf");
    if(!readBack.WorkLog().empty())
    {
        std::cerr << "Got errors reading the file:\n" << readBack.WorkLog() << "\n";
        return 3;
    }
    //and compare to original data
    //if(testOVF != readBack.
    return 0;
}
